name: Build and test on Rust Nightly

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and test
    strategy:
      matrix:
        platforms:
          - macos-13
          - macos-14
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.platforms }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - name: Build
        run: cargo +nightly build --verbose --all-features
      - name: Test
        run: cargo +nightly test --verbose --all-features
